name: Update website docs
on:
  workflow_run:
    workflows: 
      - "Build sphinx docs"
    branches:
      - 1.1[0-9]            # 1.10, 1.11, ... 1.19
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to website and update docs/site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_passphrase: ${{ secrets.PROXY_PASSPHRASE }}
          script: |
            whoami; date
            sleep 30
            hostname; date
